books = [
    {
        "id": 1,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-01",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "published_date": "2019-05-03",
        "page_count": 544,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2022-03-15",
        "page_count": 1014,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Automate the Boring Stuff",
        "author": "Al Sweigart",
        "publisher": "No Starch Press",
        "published_date": "2020-11-12",
        "page_count": 592,
        "language": "English",
    },
]
